#!/usr/bin/perl

# File generated by menutray v0.53

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit ~/.config/menutray/schema.pl instead!

use utf8;
use strict;
use Gtk3 ('-init');

my $menu = 'Gtk3::Menu'->new;
my $icon = 'Gtk3::StatusIcon'->new;

my $menutray_title   = "menutray";
my $menutray_tooltip = "Applications";

if (defined($menutray_title) and 0) {
    $icon->set_title($menutray_title);
    $icon->set_name('');
}

if (defined($menutray_tooltip) and 0) {
    $icon->set_tooltip($menutray_tooltip);
}

$icon->set_from_icon_name('start-here');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

local $SIG{USR1} = \&show_icon_menu;

load_menu();

sub show_icon_menu {
    my (undef, $event) = @_;

    if (ref($event) and $event->button == 3) {

        my $right_click = 'Gtk3::Menu'->new;
        {
            my $regenerate = 'Gtk3::ImageMenuItem'->new("_Regenerate");
            $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
            $regenerate->set_image('Gtk3::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
            $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-C\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk3'->main_quit});
            $right_click->append($regenerate);
        }

        {
            my $quit = 'Gtk3::ImageMenuItem'->new("_Quit");
            $quit->set_property('tooltip_text', "Close\ this\ application\.");
            $quit->set_image('Gtk3::Image'->new_from_icon_name("application\-exit",q{menu}));
            $quit->signal_connect('activate', sub { 'Gtk3'->main_quit });
            $right_click->append($quit);
        }

        $right_click->show_all;
        $right_click->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk3::StatusIcon::position_menu($right_click, 0, 0, $icon);
            if (1) {
                ($x, $y) = @_[1,2];
                if (0) {
                    $right_click->set_monitor(Gtk2::Gdk::Screen->get_default->get_monitor_at_point($x, $y));
                } else {
                    $right_click->set_monitor(Gtk3::Gdk::Screen::get_default()->get_monitor_at_point($x, $y));
                }
            }
            ($x, $y, @list);
        }, [1, 1], 0, 0);

        return 1;
    }
    $menu->popup(undef, undef, sub {
            my ($x, $y, @list) = Gtk3::StatusIcon::position_menu($menu, 0, 0, $icon);
            if (1) {
                ($x, $y) = @_[1,2];
                if (0) {
                    $menu->set_monitor(Gtk2::Gdk::Screen->get_default->get_monitor_at_point($x, $y));
                } else {
                    $menu->set_monitor(Gtk3::Gdk::Screen::get_default()->get_monitor_at_point($x, $y));
                }
            }
            ($x, $y, @list);
        }, [1, 1], 0, 0);

    return 1;
}

sub load_menu {
{
    my $item = 'Gtk3::ImageMenuItem'->new("_File\ Manager");
    $item->set_image('Gtk3::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ \. &"});
    $menu->append($item);
}

{
    my $item = 'Gtk3::ImageMenuItem'->new("_Terminal");
    $item->set_image('Gtk3::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $item->signal_connect('activate', sub {system "urxvtc &"});
    $menu->append($item);
}

{
    my $item = 'Gtk3::ImageMenuItem'->new("_Web\ Browser");
    $item->set_image('Gtk3::Image'->new_from_icon_name("web\-browser",q{menu}));
    $item->signal_connect('activate', sub {system "xdg\-open\ http\:\/\/ &"});
    $menu->append($item);
}

{
    my $item = 'Gtk3::ImageMenuItem'->new("_Run\ command");
    $item->set_image('Gtk3::Image'->new_from_icon_name("system\-run",q{menu}));
    $item->signal_connect('activate', sub {system "\.config\/rofi\/launch\.sh &"});
    $menu->append($item);
}


    $menu->append('Gtk3::SeparatorMenuItem'->new);

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Accessories");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_BalenaEtcher");
    $app->signal_connect('activate', sub {system "\"\/usr\/bin\/balena\-etcher\-electron\" &"});
    $app->set_property('tooltip_text', "Flash\ OS\ images\ to\ SD\ cards\ and\ USB\ drives\,\ safely\ and\ easily\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("balena\-etcher\-electron",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Bulk\ Rename");
    $app->signal_connect('activate', sub {system "thunar\ \-\-bulk\-rename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Catfish\ File\ Search");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/catfish &"});
    $app->set_property('tooltip_text', "Search\ the\ file\ system");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.catfish",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ClamTk");
    $app->signal_connect('activate', sub {system "clamtk &"});
    $app->set_property('tooltip_text', "Scan\ for\ threats\.\.\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("clamtk",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Clipboard\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-clipman &"});
    $app->set_property('tooltip_text', "Clipboard\ Manager\ Autostart\ File");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xfce4\-clipman\-plugin",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ClipIt");
    $app->signal_connect('activate', sub {system "clipit &"});
    $app->set_property('tooltip_text', "Clipboard\ Manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("clipit\-trayicon\-offline",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_compton");
    $app->signal_connect('activate', sub {system "compton &"});
    $app->set_property('tooltip_text', "A\ X\ compositor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("compton",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_DockbarX\ Preference");
    $app->signal_connect('activate', sub {system "dbx_preference &"});
    $app->set_property('tooltip_text', "Preference\ dialog\ for\ DockbarX");
    $app->set_image('Gtk3::Image'->new_from_icon_name("dockbarx",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_DockX");
    $app->signal_connect('activate', sub {system "dockx &"});
    $app->set_property('tooltip_text', "Stand\-alone\ dock\ for\ DockbarX");
    $app->set_image('Gtk3::Image'->new_from_icon_name("dockbarx",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Fcitx\ 5");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/fcitx5 &"});
    $app->set_property('tooltip_text', "Start\ Input\ Method");
    $app->set_image('Gtk3::Image'->new_from_icon_name("fcitx",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Files");
    $app->signal_connect('activate', sub {system "nautilus\ \-\-new\-window &"});
    $app->set_property('tooltip_text', "Access\ and\ organize\ files");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.gnome\.Nautilus",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Font\ Manager");
    $app->signal_connect('activate', sub {system "font\-manager &"});
    $app->set_property('tooltip_text', "Preview\,\ Compare\ and\ Manage\ Fonts");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.gnome\.FontManager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Font\ Viewer");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/font\-manager\/font\-viewer &"});
    $app->set_property('tooltip_text', "Full\ featured\ font\ file\ preview\ application");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.gnome\.FontViewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_GtkHash");
    $app->signal_connect('activate', sub {system "gtkhash &"});
    $app->set_property('tooltip_text', "Calculate\ message\ digests\ or\ checksums");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.gtkhash\.gtkhash",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Imager");
    $app->signal_connect('activate', sub {system "rpi\-imager &"});
    $app->set_property('tooltip_text', "Raspberry\ Pi\ Imager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("rpi\-imager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Keyboard\ layout\ viewer");
    $app->signal_connect('activate', sub {system "kbd\-layout\-viewer5 &"});
    $app->set_property('tooltip_text', "View\ keyboard\ layout");
    $app->set_image('Gtk3::Image'->new_from_icon_name("input\-keyboard",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Kvantum\ Manager");
    $app->signal_connect('activate', sub {system "kvantummanager &"});
    $app->set_property('tooltip_text', "A\ simple\ GUI\ for\ installing\,\ selecting\ and\ manipulating\ Kvantum\ themes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kvantum",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Menu\ Editor");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/menulibre &"});
    $app->set_property('tooltip_text', "Add\ or\ remove\ applications\ from\ the\ menu");
    $app->set_image('Gtk3::Image'->new_from_icon_name("menulibre",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Mousepad");
    $app->signal_connect('activate', sub {system "mousepad &"});
    $app->set_property('tooltip_text', "Simple\ Text\ Editor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.mousepad",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Neovim");
    $app->signal_connect('activate', sub {system "urxvtc\ \-e\ \'nvim\' &"});
    $app->set_property('tooltip_text', "Edit\ text\ files");
    $app->set_image('Gtk3::Image'->new_from_icon_name("nvim",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_nitrogen");
    $app->signal_connect('activate', sub {system "nitrogen &"});
    $app->set_property('tooltip_text', "Browse\ and\ set\ desktop\ backgrounds");
    $app->set_image('Gtk3::Image'->new_from_icon_name("nitrogen",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Notes");
    $app->signal_connect('activate', sub {system "xfce4\-notes &"});
    $app->set_property('tooltip_text', "Ideal\ for\ your\ quick\ notes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xfce4\-notes\-plugin",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Passwords\ and\ Keys");
    $app->signal_connect('activate', sub {system "seahorse &"});
    $app->set_property('tooltip_text', "Manage\ your\ passwords\ and\ encryption\ keys");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.gnome\.seahorse\.Application",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_picom");
    $app->signal_connect('activate', sub {system "picom &"});
    $app->set_property('tooltip_text', "A\ X\ compositor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("picom",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Redshift");
    $app->signal_connect('activate', sub {system "redshift\-gtk &"});
    $app->set_property('tooltip_text', "Color\ temperature\ adjustment\ tool");
    $app->set_image('Gtk3::Image'->new_from_icon_name("redshift",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Run\ Program\.\.\.");
    $app->signal_connect('activate', sub {system "xfce4\-appfinder\ \-\-collapsed &"});
    $app->set_property('tooltip_text', "Enter\ a\ command\ you\ want\ to\ launch");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.appfinder",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Screenshot");
    $app->signal_connect('activate', sub {system "xfce4\-screenshooter &"});
    $app->set_property('tooltip_text', "Take\ screenshots\ of\ the\ entire\ screen\,\ of\ the\ active\ window\ or\ of\ a\ region");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.screenshooter",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Sensor\ Viewer");
    $app->signal_connect('activate', sub {system "xfce4\-sensors &"});
    $app->set_property('tooltip_text', "Show\ sensor\ values\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xfce\-sensors",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_SpeedCrunch");
    $app->signal_connect('activate', sub {system "speedcrunch &"});
    $app->set_property('tooltip_text', "A\ high\-precision\ scientific\ calculator");
    $app->set_image('Gtk3::Image'->new_from_icon_name("speedcrunch",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Task\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-taskmanager &"});
    $app->set_property('tooltip_text', "Easy\ to\ use\ application\ to\ monitor\ system\ resources");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.taskmanager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Visual\ Studio\ Code");
    $app->signal_connect('activate', sub {system "\/opt\/visual\-studio\-code\/code\ \-\-no\-sandbox\ \-\-unity\-launch &"});
    $app->set_property('tooltip_text', "Code\ Editing\.\ Refined\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("visual\-studio\-code",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Xarchiver");
    $app->signal_connect('activate', sub {system "xarchiver &"});
    $app->set_property('tooltip_text', "A\ GTK\+\ only\ archive\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xarchiver",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Xfburn");
    $app->signal_connect('activate', sub {system "xfburn &"});
    $app->set_property('tooltip_text', "CD\ and\ DVD\ burning\ application");
    $app->set_image('Gtk3::Image'->new_from_icon_name("stock_xfburn",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Xpad");
    $app->signal_connect('activate', sub {system "xpad &"});
    $app->set_property('tooltip_text', "Jot\ down\ notes\ for\ later");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xpad",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Development");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Android\ Studio");
    $app->signal_connect('activate', sub {system "android\-studio &"});
    $app->set_property('tooltip_text', "The\ official\ Android\ IDE");
    $app->set_image('Gtk3::Image'->new_from_icon_name("android\-studio",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_DBeaver\ Community");
    $app->signal_connect('activate', sub {system "dbeaver &"});
    $app->set_property('tooltip_text', "Universal\ Database\ Manager\ and\ SQL\ Client\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("dbeaver",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Electron");
    $app->signal_connect('activate', sub {system "electron &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("electron",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Meld");
    $app->signal_connect('activate', sub {system "meld &"});
    $app->set_property('tooltip_text', "Compare\ and\ merge\ your\ files");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.gnome\.meld",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ Assistant");
    $app->signal_connect('activate', sub {system "assistant &"});
    $app->set_property('tooltip_text', "Shows\ Qt\ documentation\ and\ examples");
    $app->set_image('Gtk3::Image'->new_from_icon_name("assistant",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ Designer");
    $app->signal_connect('activate', sub {system "designer &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt\ applications");
    $app->set_image('Gtk3::Image'->new_from_icon_name("QtProject\-designer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ Linguist");
    $app->signal_connect('activate', sub {system "linguist &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt\ applications");
    $app->set_image('Gtk3::Image'->new_from_icon_name("linguist",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ QDBusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk3::Image'->new_from_icon_name("qdbusviewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Visual\ Studio\ Code");
    $app->signal_connect('activate', sub {system "\/opt\/visual\-studio\-code\/code\ \-\-no\-sandbox\ \-\-unity\-launch &"});
    $app->set_property('tooltip_text', "Code\ Editing\.\ Refined\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("visual\-studio\-code",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Education");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GAMES # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Games");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-games",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Eternal\ Senia");
    $app->signal_connect('activate', sub {system "steam\ steam\:\/\/rungameid\/351640 &"});
    $app->set_property('tooltip_text', "Play\ this\ game\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam_icon_351640",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Lutris");
    $app->signal_connect('activate', sub {system "lutris &"});
    $app->set_property('tooltip_text', "open\ source\ gaming\ platform");
    $app->set_image('Gtk3::Image'->new_from_icon_name("lutris",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Steam\ \(Runtime\)");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/steam\-runtime &"});
    $app->set_property('tooltip_text', "Steam\ 上でゲームを管理＆プレイするためのアプリケーション");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Tyrania\ \-\ A\ Kinetic\ Visual\ Novel");
    $app->signal_connect('activate', sub {system "steam\ steam\:\/\/rungameid\/1217490 &"});
    $app->set_property('tooltip_text', "Play\ this\ game\ on\ Steam");
    $app->set_image('Gtk3::Image'->new_from_icon_name("steam_icon_1217490",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Graphics");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_3D\ LUT\ Maker");
    $app->signal_connect('activate', sub {system "displaycal\-3dlut\-maker &"});
    $app->set_property('tooltip_text', "Generates\ 3D\ LUTs\ and\ ICC\ DeviceLink\ profiles");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-3dlut\-maker",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Blender");
    $app->signal_connect('activate', sub {system "blender &"});
    $app->set_property('tooltip_text', "3Dモデリング\、アニメーション\、レンダリング\、ポストプロダクションのツール");
    $app->set_image('Gtk3::Image'->new_from_icon_name("blender",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Curve\ Viewer");
    $app->signal_connect('activate', sub {system "displaycal\-curve\-viewer &"});
    $app->set_property('tooltip_text', "Shows\ calibration\ and\ ICC\ profile\ tone\ response\ curves\.\ Only\ support\ ICC\ v2\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-curve\-viewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_DisplayCAL");
    $app->signal_connect('activate', sub {system "displaycal &"});
    $app->set_property('tooltip_text', "A\ display\ calibration\ and\ profiling\ solution\ with\ a\ focus\ on\ accuracy\ and\ versatility");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Flameshot");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/flameshot &"});
    $app->set_property('tooltip_text', "Powerful\ yet\ simple\ to\ use\ screenshot\ software\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.flameshot\.Flameshot",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_FontForge");
    $app->signal_connect('activate', sub {system "fontforge &"});
    $app->set_property('tooltip_text', "An\ outline\ font\ editor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.fontforge\.FontForge",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Geeqie");
    $app->signal_connect('activate', sub {system "geeqie\ \-r &"});
    $app->set_property('tooltip_text', "View\ and\ manage\ images");
    $app->set_image('Gtk3::Image'->new_from_icon_name("geeqie",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_GNU\ Image\ Manipulation\ Program");
    $app->signal_connect('activate', sub {system "gimp\-2\.10 &"});
    $app->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gimp",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ICC\ Profile\ Info");
    $app->signal_connect('activate', sub {system "displaycal\-profile\-info &"});
    $app->set_property('tooltip_text', "Shows\ information\ about\ an\ ICC\ profile\.\ Graphs\ only\ support\ ICC\ v2\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-profile\-info",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Inkscape");
    $app->signal_connect('activate', sub {system "inkscape &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ Scalable\ Vector\ Graphics\ images");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.inkscape\.Inkscape",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Krita");
    $app->signal_connect('activate', sub {system "krita &"});
    $app->set_property('tooltip_text', "Digital\ Painting");
    $app->set_image('Gtk3::Image'->new_from_icon_name("krita",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_MComix");
    $app->signal_connect('activate', sub {system "mcomix &"});
    $app->set_property('tooltip_text', "A\ viewer\ for\ comic\ book\ archives");
    $app->set_image('Gtk3::Image'->new_from_icon_name("mcomix",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_nUFRaw");
    $app->signal_connect('activate', sub {system "nufraw &"});
    $app->set_property('tooltip_text', "A\ utility\ to\ read\ and\ manipulate\ raw\ images\ from\ digital\ cameras");
    $app->set_image('Gtk3::Image'->new_from_icon_name("nufraw",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Peek");
    $app->signal_connect('activate', sub {system "peek &"});
    $app->set_property('tooltip_text', "Record\ short\ animated\ GIF\ images\ from\ your\ screen");
    $app->set_image('Gtk3::Image'->new_from_icon_name("com\.uploadedlobster\.peek",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Profile\ Loader");
    $app->signal_connect('activate', sub {system "displaycal\-apply\-profiles\ \-\-force &"});
    $app->set_property('tooltip_text', "Sets\ ICC\ profiles\ and\ loads\ calibration\ curves\ for\ all\ configured\ display\ devices");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-apply\-profiles",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_QtQR");
    $app->signal_connect('activate', sub {system "qtqr &"});
    $app->set_property('tooltip_text', "Create\ and\ decode\ QR\ Codes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("qtqr",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Ristretto\ Image\ Viewer");
    $app->signal_connect('activate', sub {system "ristretto &"});
    $app->set_property('tooltip_text', "Look\ at\ your\ images\ easily");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.ristretto",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Scripting\ Client");
    $app->signal_connect('activate', sub {system "displaycal\-scripting\-client &"});
    $app->set_property('tooltip_text', "Control\ DisplayCAL\ via\ simple\ scripting\ commands");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-scripting\-client",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Synthetic\ ICC");
    $app->signal_connect('activate', sub {system "displaycal\-synthprofile &"});
    $app->set_property('tooltip_text', "Creates\ ICC\ profiles\ of\ synthetic\ RGB\ colorspaces");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-synthprofile",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Testchart\ Editor");
    $app->signal_connect('activate', sub {system "displaycal\-testchart\-editor &"});
    $app->set_property('tooltip_text', "A\ testchart\ editor\ and\ creator\ for\ RGB\ testcharts\ in\ ArgyllCMS\ CGATS\ format");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-testchart\-editor",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_VRML\ to\ X3D");
    $app->signal_connect('activate', sub {system "displaycal\-vrml\-to\-x3d\-converter &"});
    $app->set_property('tooltip_text', "Converts\ VRML\ files\ to\ X3D\ embedded\ in\ HTML");
    $app->set_image('Gtk3::Image'->new_from_icon_name("displaycal\-vrml\-to\-x3d\-converter",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_XSane\ \-\ Scanning");
    $app->signal_connect('activate', sub {system "xsane &"});
    $app->set_property('tooltip_text', "Acquire\ images\ from\ a\ scanner");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xsane",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Multimedia");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Cantata");
    $app->signal_connect('activate', sub {system "cantata &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("cantata",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_HandBrake");
    $app->signal_connect('activate', sub {system "ghb &"});
    $app->set_property('tooltip_text', "Transcodes\ DVD\,\ Bluray\,\ and\ other\ media");
    $app->set_image('Gtk3::Image'->new_from_icon_name("fr\.handbrake\.ghb",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_mpv\ Media\ Player");
    $app->signal_connect('activate', sub {system "mpv\ \-\-player\-operation\-mode\=pseudo\-gui\ \-\- &"});
    $app->set_property('tooltip_text', "Play\ movies\ and\ songs");
    $app->set_image('Gtk3::Image'->new_from_icon_name("mpv",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_OBS\ Studio");
    $app->signal_connect('activate', sub {system "obs &"});
    $app->set_property('tooltip_text', "Free\ and\ Open\ Source\ Streaming\/Recording\ Software");
    $app->set_image('Gtk3::Image'->new_from_icon_name("com\.obsproject\.Studio",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Parole\ Media\ Player");
    $app->signal_connect('activate', sub {system "parole &"});
    $app->set_property('tooltip_text', "Play\ your\ media");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.parole",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Peek");
    $app->signal_connect('activate', sub {system "peek &"});
    $app->set_property('tooltip_text', "Record\ short\ animated\ GIF\ images\ from\ your\ screen");
    $app->set_image('Gtk3::Image'->new_from_icon_name("com\.uploadedlobster\.peek",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_PulseAudio\ Volume\ Control");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Adjust\ the\ volume\ level");
    $app->set_image('Gtk3::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk3::Image'->new_from_icon_name("qv4l2",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt\ V4L2\ video\ capture\ utility");
    $app->signal_connect('activate', sub {system "qvidcap &"});
    $app->set_property('tooltip_text', "Viewer\ for\ video\ capture");
    $app->set_image('Gtk3::Image'->new_from_icon_name("qvidcap",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_SMPlayer");
    $app->signal_connect('activate', sub {system "smplayer &"});
    $app->set_property('tooltip_text', "高性能\ MPlayer\ フロントエンド");
    $app->set_image('Gtk3::Image'->new_from_icon_name("smplayer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Spotify");
    $app->signal_connect('activate', sub {system "spotify &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("spotify\-client",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_VLCメディアプレイヤー");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vlc\ \-\-started\-from\-file &"});
    $app->set_property('tooltip_text', "マルチメディアストリームの読み込み\、キャプチャー\、ブロードキャスト");
    $app->set_image('Gtk3::Image'->new_from_icon_name("vlc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Volume\ Icon");
    $app->signal_connect('activate', sub {system "volumeicon &"});
    $app->set_property('tooltip_text', "Lightweight\ volume\ control\ for\ the\ systray");
    $app->set_image('Gtk3::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Xfburn");
    $app->signal_connect('activate', sub {system "xfburn &"});
    $app->set_property('tooltip_text', "CD\ and\ DVD\ burning\ application");
    $app->set_image('Gtk3::Image'->new_from_icon_name("stock_xfburn",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Network");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Birdtray");
    $app->signal_connect('activate', sub {system "birdtray &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("com\.ulduzsoft\.Birdtray",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Discord");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/discord &"});
    $app->set_property('tooltip_text', "All\-in\-one\ voice\ and\ text\ chat\ for\ gamers\ that\'s\ free\,\ secure\,\ and\ works\ on\ both\ your\ desktop\ and\ phone\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("discord",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_FileZilla");
    $app->signal_connect('activate', sub {system "filezilla &"});
    $app->set_property('tooltip_text', "Download\ and\ upload\ files\ via\ FTP\,\ FTPS\ and\ SFTP");
    $app->set_image('Gtk3::Image'->new_from_icon_name("filezilla",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Firefox\ Developer\ Edition");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/firefox\-developer\-edition\/firefox &"});
    $app->set_property('tooltip_text', "ウェブを閲覧します");
    $app->set_image('Gtk3::Image'->new_from_icon_name("firefox\-developer\-edition",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Google\ Chrome");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/google\-chrome\-stable &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk3::Image'->new_from_icon_name("google\-chrome",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_HexChat");
    $app->signal_connect('activate', sub {system "hexchat\ \-\-existing &"});
    $app->set_property('tooltip_text', "Chat\ with\ other\ people\ online");
    $app->set_image('Gtk3::Image'->new_from_icon_name("hexchat",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_JDim\ 2ch\ browser");
    $app->signal_connect('activate', sub {system "\/home\/lamt\/bin\/jd\.sh &"});
    $app->set_property('tooltip_text', "JDim\ is\ a\ 2ch\ browser\ based\ on\ gtkmm\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("jdim",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Remmina");
    $app->signal_connect('activate', sub {system "remmina\-file\-wrapper &"});
    $app->set_property('tooltip_text', "Connect\ to\ remote\ desktops");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.remmina\.Remmina",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Slack");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/slack\ \-s &"});
    $app->set_property('tooltip_text', "Slack\ Desktop");
    $app->set_image('Gtk3::Image'->new_from_icon_name("slack",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Thunderbird");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/thunderbird\/thunderbird &"});
    $app->set_property('tooltip_text', "Send\ and\ receive\ mail\ with\ Thunderbird");
    $app->set_image('Gtk3::Image'->new_from_icon_name("thunderbird",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Transmission");
    $app->signal_connect('activate', sub {system "transmission\-gtk &"});
    $app->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app->set_image('Gtk3::Image'->new_from_icon_name("transmission",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_twinux");
    $app->signal_connect('activate', sub {system "env\ BAMF_DESKTOP_FILE_HINT\=\/var\/lib\/snapd\/desktop\/applications\/twinux_twinux\.desktop\ \/var\/lib\/snapd\/snap\/bin\/twinux &"});
    $app->set_property('tooltip_text', "Twitter\ Client\ for\ Linux\,\ MacOS\ and\ Windows\/");
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/var\/lib\/snapd\/snap\/twinux\/62\/meta\/gui\/icon\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_uGet");
    $app->signal_connect('activate', sub {system "uget\-gtk &"});
    $app->set_property('tooltip_text', "Download\ multiple\ URLs\ and\ apply\ it\ to\ one\ of\ setting\/queue\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("uget\-icon",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Wireshark");
    $app->signal_connect('activate', sub {system "wireshark &"});
    $app->set_property('tooltip_text', "Network\ traffic\ analyzer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("wireshark",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Office");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Calibre");
    $app->signal_connect('activate', sub {system "calibre\ \-\-detach &"});
    $app->set_property('tooltip_text', "E\-book\ library\ management\:\ Convert\,\ view\,\ share\,\ catalogue\ all\ your\ e\-books");
    $app->set_image('Gtk3::Image'->new_from_icon_name("calibre\-gui",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Dictionary");
    $app->signal_connect('activate', sub {system "xfce4\-dict &"});
    $app->set_property('tooltip_text', "A\ client\ program\ to\ query\ different\ dictionaries\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.Dictionary",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_E\-book\ editor");
    $app->signal_connect('activate', sub {system "ebook\-edit\ \-\-detach &"});
    $app->set_property('tooltip_text', "Edit\ E\-books\ in\ various\ formats");
    $app->set_image('Gtk3::Image'->new_from_icon_name("calibre\-ebook\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_E\-book\ viewer");
    $app->signal_connect('activate', sub {system "ebook\-viewer\ \-\-detach &"});
    $app->set_property('tooltip_text', "Viewer\ for\ E\-books\ in\ all\ the\ major\ formats");
    $app->set_image('Gtk3::Image'->new_from_icon_name("calibre\-viewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ePDFViewer");
    $app->signal_connect('activate', sub {system "epdfview &"});
    $app->set_property('tooltip_text', "Lightweight\ PDF\ document\ viewer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("epdfview",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Joplin");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/joplin\-desktop &"});
    $app->set_property('tooltip_text', "Joplin\ \-\ a\ note\ taking\ and\ to\-do\ application\ with\ synchronization\ capabilities\ for\ Windows\,\ macOS\,\ Linux\,\ Android\ and\ iOS\.");
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/joplin\-desktop\/resources\/build\/icons\/128x128\.png",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice");
    $app->signal_connect('activate', sub {system "libreoffice &"});
    $app->set_property('tooltip_text', "The\ office\ productivity\ suite\ compatible\ to\ the\ open\ and\ standardized\ ODF\ document\ format\.\ Supported\ by\ The\ Document\ Foundation\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-startcenter",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Base");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-base &"});
    $app->set_property('tooltip_text', "Manage\ databases\,\ create\ queries\ and\ reports\ to\ track\ and\ manage\ your\ information\ by\ using\ Base\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-base",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Calc");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-calc &"});
    $app->set_property('tooltip_text', "Perform\ calculations\,\ analyze\ information\ and\ manage\ lists\ in\ spreadsheets\ by\ using\ Calc\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-calc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Impress");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-impress &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ presentations\ for\ slideshows\,\ meeting\ and\ Web\ pages\ by\ using\ Impress\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-impress",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LibreOffice\ Writer");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-writer &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ text\ and\ graphics\ in\ letters\,\ reports\,\ documents\ and\ Web\ pages\ by\ using\ Writer\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("libreoffice\-writer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LRF\ viewer");
    $app->signal_connect('activate', sub {system "lrfviewer &"});
    $app->set_property('tooltip_text', "Viewer\ for\ LRF\ files\ \(SONY\ ebook\ format\ files\)");
    $app->set_image('Gtk3::Image'->new_from_icon_name("calibre\-viewer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Osmo");
    $app->signal_connect('activate', sub {system "osmo &"});
    $app->set_property('tooltip_text', "Personal\ Organizer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("osmo",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Zathura");
    $app->signal_connect('activate', sub {system "zathura &"});
    $app->set_property('tooltip_text', "A\ minimalistic\ document\ viewer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.pwmt\.zathura",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # OTHER # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Other");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-other",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_imdb");
    $app->signal_connect('activate', sub {system " &"});
    $app->set_image('Gtk3::Image'->new_from_stock(q{gtk-missing-image},q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_my\-weather\-indicator");
    $app->signal_connect('activate', sub {system " &"});
    $app->set_image('Gtk3::Image'->new_from_stock(q{gtk-missing-image},q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Settings");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_About\ Me");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/mugshot &"});
    $app->set_property('tooltip_text', "Configure\ your\ profile\ image\ and\ contact\ details");
    $app->set_image('Gtk3::Image'->new_from_icon_name("mugshot",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Accessibility");
    $app->signal_connect('activate', sub {system "xfce4\-accessibility\-settings &"});
    $app->set_property('tooltip_text', "Improve\ keyboard\ and\ mouse\ accessibility");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.accessibility",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Advanced\ Network\ Configuration");
    $app->signal_connect('activate', sub {system "nm\-connection\-editor &"});
    $app->set_property('tooltip_text', "Manage\ and\ change\ your\ network\ connection\ settings");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-system\-network",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Appearance");
    $app->signal_connect('activate', sub {system "xfce4\-appearance\-settings &"});
    $app->set_property('tooltip_text', "Customize\ the\ look\ of\ your\ desktop");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.appearance",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ARandR");
    $app->signal_connect('activate', sub {system "arandr &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("display",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Bluetooth\ Adapters");
    $app->signal_connect('activate', sub {system "blueman\-adapters &"});
    $app->set_property('tooltip_text', "Set\ Bluetooth\ Adapter\ Properties");
    $app->set_image('Gtk3::Image'->new_from_icon_name("blueman\-device",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Bluetooth\ Manager");
    $app->signal_connect('activate', sub {system "blueman\-manager &"});
    $app->set_property('tooltip_text', "Blueman\ Bluetooth\ Manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("blueman",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Clipboard\ Manager\ Settings");
    $app->signal_connect('activate', sub {system "xfce4\-clipman\-settings &"});
    $app->set_property('tooltip_text', "Customize\ your\ clipboard");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xfce4\-clipman\-plugin",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Color\ Profiles");
    $app->signal_connect('activate', sub {system "xfce4\-color\-settings &"});
    $app->set_property('tooltip_text', "Set\ color\ profiles");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.color",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Customize\ Look\ and\ Feel");
    $app->signal_connect('activate', sub {system "lxappearance &"});
    $app->set_property('tooltip_text', "Customizes\ look\ and\ feel\ of\ your\ desktop\ and\ applications");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Default\ Applications");
    $app->signal_connect('activate', sub {system "xfce4\-mime\-settings &"});
    $app->set_property('tooltip_text', "Associate\ preferred\ applications\ with\ MIME\ types");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.default\-applications",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Desktop");
    $app->signal_connect('activate', sub {system "xfdesktop\-settings &"});
    $app->set_property('tooltip_text', "Set\ desktop\ background\ and\ menu\ and\ icon\ behavior");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.xfdesktop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Display");
    $app->signal_connect('activate', sub {system "xfce4\-display\-settings &"});
    $app->set_property('tooltip_text', "Configure\ screen\ settings\ and\ layout");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.display",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Fcitx\ 5\ Configuration");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/fcitx5\-configtool &"});
    $app->set_property('tooltip_text', "Change\ Fcitx\ 5\ Configuration");
    $app->set_image('Gtk3::Image'->new_from_icon_name("fcitx",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Fcitx\ 5\ Migration\ Wizard");
    $app->signal_connect('activate', sub {system "fcitx5\-migrator &"});
    $app->set_property('tooltip_text', "Launch\ the\ wizard\ to\ import\ data\ from\ other\ input\ method\ as\ Fcitx\ 4\ etc\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("fcitx",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_File\ Manager\ Settings");
    $app->signal_connect('activate', sub {system "thunar\-settings &"});
    $app->set_property('tooltip_text', "Configure\ the\ Thunar\ file\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Firewall\ Configuration");
    $app->signal_connect('activate', sub {system "gufw &"});
    $app->set_property('tooltip_text', "An\ easy\ way\ to\ configure\ your\ firewall");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gufw",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Keyboard");
    $app->signal_connect('activate', sub {system "xfce4\-keyboard\-settings &"});
    $app->set_property('tooltip_text', "Edit\ keyboard\ settings\ and\ application\ shortcuts");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.keyboard",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Kvantum\ Manager");
    $app->signal_connect('activate', sub {system "kvantummanager &"});
    $app->set_property('tooltip_text', "A\ simple\ GUI\ for\ installing\,\ selecting\ and\ manipulating\ Kvantum\ themes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("kvantum",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Menu\ Editor");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/menulibre &"});
    $app->set_property('tooltip_text', "Add\ or\ remove\ applications\ from\ the\ menu");
    $app->set_image('Gtk3::Image'->new_from_icon_name("menulibre",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Mouse\ and\ Touchpad");
    $app->signal_connect('activate', sub {system "xfce4\-mouse\-settings &"});
    $app->set_property('tooltip_text', "Configure\ pointer\ device\ behavior\ and\ appearance");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.mouse",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Notifications");
    $app->signal_connect('activate', sub {system "xfce4\-notifyd\-config &"});
    $app->set_property('tooltip_text', "Customize\ how\ notifications\ appear\ on\ your\ screen");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.notification",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_NVIDIA\ 設定");
    $app->signal_connect('activate', sub {system "optirun\ \-b\ none\ nvidia\-settings\ \-c\ \:8 &"});
    $app->set_property('tooltip_text', "NVIDIA\ X\ Server\ Settings");
    $app->set_image('Gtk3::Image'->new_from_icon_name("nvidia\-settings",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Panel");
    $app->signal_connect('activate', sub {system "xfce4\-panel\ \-\-preferences &"});
    $app->set_property('tooltip_text', "Customize\ the\ panel");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.panel",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Power\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-power\-manager\-settings &"});
    $app->set_property('tooltip_text', "Settings\ for\ the\ Xfce\ Power\ Manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.powermanager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("printer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_PulseAudio\ Volume\ Control");
    $app->signal_connect('activate', sub {system "pavucontrol &"});
    $app->set_property('tooltip_text', "Adjust\ the\ volume\ level");
    $app->set_image('Gtk3::Image'->new_from_icon_name("multimedia\-volume\-control",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Qt5\ Settings");
    $app->signal_connect('activate', sub {system "qt5ct &"});
    $app->set_property('tooltip_text', "Qt5\ Configuration\ Tool");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-desktop\-theme",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Removable\ Drives\ and\ Media");
    $app->signal_connect('activate', sub {system "thunar\-volman\-settings &"});
    $app->set_property('tooltip_text', "Configure\ management\ of\ removable\ drives\ and\ media");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.volman",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Screensaver");
    $app->signal_connect('activate', sub {system "xfce4\-screensaver\-preferences &"});
    $app->set_property('tooltip_text', "Set\ your\ screensaver\ preferences");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.ScreenSaver",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Screensaver");
    $app->signal_connect('activate', sub {system "xscreensaver\-settings &"});
    $app->set_property('tooltip_text', "Change\ screensaver\ properties");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xscreensaver",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Session\ and\ Startup");
    $app->signal_connect('activate', sub {system "xfce4\-session\-settings &"});
    $app->set_property('tooltip_text', "Customize\ desktop\ startup");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.session",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Settings\ Editor");
    $app->signal_connect('activate', sub {system "xfce4\-settings\-editor &"});
    $app->set_property('tooltip_text', "Graphical\ settings\ editor\ for\ Xfconf");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.editor",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Settings\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-settings\-manager &"});
    $app->set_property('tooltip_text', "Graphical\ Settings\ Manager\ for\ Xfce");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.settings\.manager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Text\ Editor\ Settings");
    $app->signal_connect('activate', sub {system "mousepad\ \-\-preferences &"});
    $app->set_property('tooltip_text', "Configure\ the\ Mousepad\ text\ editor");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.mousepad",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_TLP\ UI");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/tlpui &"});
    $app->set_property('tooltip_text', "Configuration\ interface");
    $app->set_image('Gtk3::Image'->new_from_icon_name("tlpui",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Window\ Manager");
    $app->signal_connect('activate', sub {system "xfwm4\-settings &"});
    $app->set_property('tooltip_text', "Configure\ window\ behavior\ and\ shortcuts");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.xfwm4",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Window\ Manager\ Tweaks");
    $app->signal_connect('activate', sub {system "xfwm4\-tweaks\-settings &"});
    $app->set_property('tooltip_text', "Fine\-tune\ window\ behaviour\ and\ effects");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.xfwm4\-tweaks",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Workspaces");
    $app->signal_connect('activate', sub {system "xfwm4\-workspace\-settings &"});
    $app->set_property('tooltip_text', "Configure\ layout\,\ names\ and\ margins");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.workspaces",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Xfce\ Terminal\ Settings");
    $app->signal_connect('activate', sub {system "xfce4\-terminal\ \-\-preferences &"});
    $app->set_property('tooltip_text', "Configure\ Xfce\ Terminal");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.terminal\-settings",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_System");
    $app->set_image('Gtk3::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Alacritty");
    $app->signal_connect('activate', sub {system "alacritty &"});
    $app->set_property('tooltip_text', "A\ fast\,\ cross\-platform\,\ OpenGL\ terminal\ emulator");
    $app->set_image('Gtk3::Image'->new_from_icon_name("Alacritty",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk3::Image'->new_from_icon_name("network\-wired",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Bulk\ Rename");
    $app->signal_connect('activate', sub {system "thunar\ \-\-bulk\-rename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_conky");
    $app->signal_connect('activate', sub {system "conky\ \-\-daemonize\ \-\-pause\=1 &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("conky\-logomark\-violet",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_dconf\ Editor");
    $app->signal_connect('activate', sub {system "dconf\-editor &"});
    $app->set_property('tooltip_text', "Directly\ edit\ your\ entire\ configuration\ database");
    $app->set_image('Gtk3::Image'->new_from_icon_name("ca\.desrt\.dconf\-editor",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Fcitx\ 5");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/fcitx5 &"});
    $app->set_property('tooltip_text', "Start\ Input\ Method");
    $app->set_image('Gtk3::Image'->new_from_icon_name("fcitx",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_GParted");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/gparted &"});
    $app->set_property('tooltip_text', "Create\,\ reorganize\,\ and\ delete\ partitions");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gparted",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_GSmartControl");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/gsmartcontrol_polkit &"});
    $app->set_property('tooltip_text', "Monitor\ and\ control\ SMART\ data\ on\ hard\ disk\ and\ solid\-state\ drives");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gsmartcontrol",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Hardware\ Locality\ lstopo");
    $app->signal_connect('activate', sub {system "lstopo &"});
    $app->set_property('tooltip_text', "Show\ hardware\ topology");
    $app->set_image('Gtk3::Image'->new_from_icon_name("hwloc",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Htop");
    $app->signal_connect('activate', sub {system "urxvtc\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk3::Image'->new_from_icon_name("htop",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Log\ Out");
    $app->signal_connect('activate', sub {system "xfce4\-session\-logout &"});
    $app->set_property('tooltip_text', "Log\ out\ of\ the\ Xfce\ Desktop");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xfsm\-logout",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_LSHW");
    $app->signal_connect('activate', sub {system "\/usr\/sbin\/gtk\-lshw &"});
    $app->set_property('tooltip_text', "HardWare\ LiSter");
    $app->set_image('Gtk3::Image'->new_from_pixbuf('Gtk3::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/lshw\/artwork\/logo\.svg",16,16)));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Manage\ Printing");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/xdg\-open\ http\:\/\/localhost\:631\/ &"});
    $app->set_property('tooltip_text', "CUPS\ Web\ Interface");
    $app->set_image('Gtk3::Image'->new_from_icon_name("cups",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Octopi");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/octopi &"});
    $app->set_property('tooltip_text', "Add\ or\ remove\ software\ installed\ on\ the\ system");
    $app->set_image('Gtk3::Image'->new_from_icon_name("octopi",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Octopi\ CacheCleaner");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/octopi\-cachecleaner &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("octopi",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_OpenJDK\ Java\ 16\ Console");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/jvm\/java\-16\-openjdk\/bin\/jconsole &"});
    $app->set_property('tooltip_text', "OpenJDK\ Java\ 16\ Monitoring\ \&\ Management\ Console");
    $app->set_image('Gtk3::Image'->new_from_icon_name("java16\-openjdk",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_OpenJDK\ Java\ 16\ Shell");
    $app->signal_connect('activate', sub {system "urxvtc\ \-e\ \'\/usr\/lib\/jvm\/java\-16\-openjdk\/bin\/jshell\' &"});
    $app->set_property('tooltip_text', "OpenJDK\ Java\ 16\ Shell");
    $app->set_image('Gtk3::Image'->new_from_icon_name("java16\-openjdk",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Oracle\ VM\ VirtualBox");
    $app->signal_connect('activate', sub {system "VirtualBox &"});
    $app->set_property('tooltip_text', "Run\ several\ virtual\ systems\ on\ a\ single\ host\ computer");
    $app->set_image('Gtk3::Image'->new_from_icon_name("virtualbox",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Pacman\ Log\ Viewer");
    $app->signal_connect('activate', sub {system "plv &"});
    $app->set_property('tooltip_text', "Inspect\ pacman\ log");
    $app->set_image('Gtk3::Image'->new_from_icon_name("plv",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Print\ Settings");
    $app->signal_connect('activate', sub {system "system\-config\-printer &"});
    $app->set_property('tooltip_text', "Configure\ printers");
    $app->set_image('Gtk3::Image'->new_from_icon_name("printer",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Psensor");
    $app->signal_connect('activate', sub {system "psensor &"});
    $app->set_property('tooltip_text', "Psensor\ is\ a\ graphical\ temperature\ monitor\ for\ Linux");
    $app->set_image('Gtk3::Image'->new_from_icon_name("psensor",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_QDirStat");
    $app->signal_connect('activate', sub {system "qdirstat &"});
    $app->set_image('Gtk3::Image'->new_from_icon_name("qdirstat",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_ranger");
    $app->signal_connect('activate', sub {system "urxvtc\ \-e\ \'ranger\' &"});
    $app->set_property('tooltip_text', "Launches\ the\ ranger\ file\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Sensor\ Viewer");
    $app->signal_connect('activate', sub {system "xfce4\-sensors &"});
    $app->set_property('tooltip_text', "Show\ sensor\ values\.");
    $app->set_image('Gtk3::Image'->new_from_icon_name("xfce\-sensors",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Snapper\ GUI");
    $app->signal_connect('activate', sub {system "snapper\-gui &"});
    $app->set_property('tooltip_text', "Frontend\ for\ snapper\ snapshot\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("drive\-harddisk",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_System\ Profiler\ and\ Benchmark");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/hardinfo &"});
    $app->set_property('tooltip_text', "Displays\ system\ information");
    $app->set_image('Gtk3::Image'->new_from_icon_name("hardinfo",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Task\ Manager");
    $app->signal_connect('activate', sub {system "xfce4\-taskmanager &"});
    $app->set_property('tooltip_text', "Easy\ to\ use\ application\ to\ monitor\ system\ resources");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.taskmanager",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.thunar",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_urxvt");
    $app->signal_connect('activate', sub {system "urxvt &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone");
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_urxvt\ \(client\)");
    $app->signal_connect('activate', sub {system "urxvtc &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone\ client\ for\ urxvtd");
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_urxvt\ \(tabbed\)");
    $app->signal_connect('activate', sub {system "urxvt\-tabbed &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ and\ tabbed\ rxvt\ clone");
    $app->set_image('Gtk3::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_VeraCrypt");
    $app->signal_connect('activate', sub {system "veracrypt &"});
    $app->set_property('tooltip_text', "Disk\ encryption\ with\ strong\ security\ based\ on\ TrueCrypt");
    $app->set_image('Gtk3::Image'->new_from_icon_name("veracrypt",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Xfce\ Terminal");
    $app->signal_connect('activate', sub {system "xfce4\-terminal &"});
    $app->set_property('tooltip_text', "Terminal\ Emulator");
    $app->set_image('Gtk3::Image'->new_from_icon_name("org\.xfce\.terminal",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $menu1 = 'Gtk3::Menu'->new;
    my $app = 'Gtk3::ImageMenuItem'->new("_Menutray");
    $app->set_image('Gtk3::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Config");
    $app->signal_connect('activate', sub {system "mousepad\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/config\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Menu");
    $app->signal_connect('activate', sub {system "mousepad\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
{
    my $app = 'Gtk3::ImageMenuItem'->new("_Schema");
    $app->signal_connect('activate', sub {system "mousepad\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/schema\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk3::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $menu1->append($app);
}
    $app->set_submenu($menu1);
    $menu->append($app);
}

    $menu->append('Gtk3::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk3::ImageMenuItem'->new("_Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk3::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-C\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/lamt\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk3'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk3::ImageMenuItem'->new("_Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk3::Image'->new_from_icon_name("application\-exit",q{menu}));
    $quit->signal_connect('activate', sub { 'Gtk3'->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk3'->main;
